#!/bin/bash

# Go to this directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
which apt-get 2> /dev/null >&2
if [ $? -eq 0 ]; then
    MODE="apt"
else
    which yum 2> /dev/null >&2
    if [ $? -eq 0 ]; then
        MODE="yum"
    else
        echo "I can't found apt or yum"
        exit 1
    fi
fi

if [ $# -lt 2 ]; then
    echo "Usage: "
    echo "  notroot [search|install] package"
    echo ""
    echo "  search package:"
    echo "		Display the search result for a package"
    echo ""
    echo "  install packages:"
    echo "		Installs a given package"
    echo ""
    echo "Note: don't forget to source notroot/bashrc"
    exit 1
fi

case $1 in
    search)
        if [ "$MODE" = "apt" ]; then
            apt-cache search $2
        fi
        if [ "$MODE" = "yum" ]; then
            yum search $2
        fi
        ;;
    install)
        shift
        for package in $*; do
        echo "Installing $package from $MODE..."
            if [ "$MODE" = "apt" ]; then
                rm -rf deb
                mkdir deb &&
                cd deb &&
                apt-get download $package &&
                cd .. &&
                dpkg -x deb/*.deb . 
            fi
            if [ "$MODE" = "yum" ]; then
                rm -rf rpm
                mkdir rpm &&
                cd rpm &&
                yumdownloader $package &&
                cd .. &&
                rpm2cpio rpm/*.rpm | cpio -idmvu
            fi
        done
        ;;
    *)
        echo "Unknown instruction $1"
        ;;
esac
